// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhTtTEp_KiSmPVVLQR9-sQQICxbja0YGQ',
    appId: '1:735435150869:web:d927afe57963608c50a01c',
    messagingSenderId: '735435150869',
    projectId: 'travelairplane-ef28e',
    authDomain: 'travelairplane-ef28e.firebaseapp.com',
    storageBucket: 'travelairplane-ef28e.appspot.com',
    measurementId: 'G-GEVP2J7NVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoyqXXbUfi6KeKReEqDqLIwuH6KIhn9ao',
    appId: '1:735435150869:android:c2da3a1b52844a2b50a01c',
    messagingSenderId: '735435150869',
    projectId: 'travelairplane-ef28e',
    storageBucket: 'travelairplane-ef28e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY8ZLr7GiE5xm2WxoEovFC3nOi4VHhw8o',
    appId: '1:735435150869:ios:13162d136679ee0150a01c',
    messagingSenderId: '735435150869',
    projectId: 'travelairplane-ef28e',
    storageBucket: 'travelairplane-ef28e.appspot.com',
    iosClientId: '735435150869-gaqd5i8op9m1j3122qas0auvre960u5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTravelBwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY8ZLr7GiE5xm2WxoEovFC3nOi4VHhw8o',
    appId: '1:735435150869:ios:13162d136679ee0150a01c',
    messagingSenderId: '735435150869',
    projectId: 'travelairplane-ef28e',
    storageBucket: 'travelairplane-ef28e.appspot.com',
    iosClientId: '735435150869-gaqd5i8op9m1j3122qas0auvre960u5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTravelBwa',
  );
}
